function Hd = halfband
%HALFBAND Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Apr-2017 19:23:19

% FIR Window Halfband lowpass filter designed using the FIRHALFBAND
% function.

% All frequency values are in MHz.
Fs = 6.25;  % Sampling Frequency

N    = 10;   % Order
Beta = 0.5;  % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firhalfband(N, win);
Hd = dfilt.dffir(b);

% [EOF]
